openapi: 3.0.1
info:
  title:  API carts section
  description: la ruta carts 
  version: 1.0.0

paths:
  /api/carts/:
    get:
      summary: Obtiene un array con todos los carritos o un carrito por su id(/api/carts/)
      tags:
        - carts
      parameters:
        - name: cid
          in: query
          description: parámetro opcional, buscar un carrito por su id (/api/carts/idDelCarrito)
          schema:
            type: string
  
      responses:
        "200":
          description: Se obtuvo el recurso de la base de datos
        "500":
          description: Error interno en el servidor
  
    post:
      summary: crecibe un id de objeto usuario por query params y crea un nuevo objeto carrito el cual es agregado al array carts del usuario
      tags:
        - carts
      parameters:
        - name: uid
          in: query
          description: parametro obligatorio para buscar al usuario en la base de datos. 
          schema:
            type: string
      responses:
        "200":
          description: Se obtuvo el recurso de la base de datos
        "500":
          description: Error interno en el servidor
      

components:
  schemas:
    cart:
      type: object
      properties:
        _id:
          type: string
          description: Id auto generado por mongoose
        products:
          type: array
          description: Contiene los productos agregados en el carrito
          items:
            type: object
            properties:
              item:
                type: string
                description: ID de un objeto producto que representa a dicho objeto (referencia)
              quantity:
                type: number
                description: Cantidad del producto agregado, por defecto es 1 al momento de agregar un producto si no se especifica su cantidad
